"""Independent RCI-AD status dimensions from the canonical architecture."""
from __future__ import annotations
from enum import Enum

class ResourceStatus(str, Enum):
    NORMAL="NORMAL"; ELEVATED="ELEVATED"; HIGH="HIGH"; CRITICAL="CRITICAL"
class CommunicationStatus(str, Enum):
    NORMAL="NORMAL"; ELEVATED="ELEVATED"; HIGH="HIGH"; CRITICAL="CRITICAL"
class InterfaceStatus(str, Enum):
    DISCONNECTED="DISCONNECTED"; CONNECTED="CONNECTED"; ACTIVE="ACTIVE"; DEGRADED="DEGRADED"; SUSPICIOUS="SUSPICIOUS"; ISOLATED="ISOLATED"
class DataStatus(str, Enum):
    VALID="VALID"; OVERSIZE="OVERSIZE"; HIGH_COST="HIGH_COST"; INVALID="INVALID"
class DeviceStatus(str, Enum):
    UNKNOWN="UNKNOWN"; DISCOVERED="DISCOVERED"; ACTIVE="ACTIVE"; DEGRADED="DEGRADED"; SUSPICIOUS="SUSPICIOUS"; QUARANTINED="QUARANTINED"; REVOKED="REVOKED"
class ModuleStatus(str, Enum):
    ACTIVE="ACTIVE"; DEGRADED="DEGRADED"; SUSPICIOUS="SUSPICIOUS"; QUARANTINED="QUARANTINED"; REVOKED="REVOKED"
class LearningStatus(str, Enum):
    UNSEEN="UNSEEN"; LEARNING="LEARNING"; ESTABLISHED="ESTABLISHED"; FROZEN="FROZEN"; INVALID="INVALID"
class ModelStatus(str, Enum):
    UNINITIALIZED="UNINITIALIZED"; VALIDATING="VALIDATING"; VALID="VALID"; DEGRADED="DEGRADED"; INVALID="INVALID"
class ConfidenceStatus(str, Enum):
    UNKNOWN="UNKNOWN"; LOW="LOW"; MEDIUM="MEDIUM"; HIGH="HIGH"
class IntegrityStatus(str, Enum):
    UNVERIFIED="UNVERIFIED"; VERIFIED="VERIFIED"; MODIFIED="MODIFIED"; COMPROMISED="COMPROMISED"
class TrustStatus(str, Enum):
    UNTRUSTED="UNTRUSTED"; TRUSTED="TRUSTED"; REVOKED="REVOKED"
class CommunicatorStatus(str, Enum):
    STARTING="STARTING"; READY="READY"; DEGRADED="DEGRADED"; COMPROMISED="COMPROMISED"; ISOLATED="ISOLATED"
class DefenseStatus(str, Enum):
    READY="READY"; OBSERVING="OBSERVING"; ACTIVE="ACTIVE"; CONTAINMENT="CONTAINMENT"; RECOVERY="RECOVERY"
class RecoveryStatus(str, Enum):
    NONE="NONE"; REQUIRED="REQUIRED"; VERIFYING="VERIFYING"; RESTORING="RESTORING"; VALIDATING="VALIDATING"; COMPLETE="COMPLETE"; FAILED="FAILED"
